[build]
  command = "NODE_OPTIONS='--max-old-space-size=4096' npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18.17.0"
  NPM_FLAGS = "--production=false"
  NEXT_TELEMETRY_DISABLED = "1"
  NODE_OPTIONS = "--max-old-space-size=4096"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  external_node_modules = ["@prisma/client", "prisma"]
